import {
  Controller,
  Post,
  Headers,
  Req,
  HttpCode,
  HttpStatus,
  BadRequestException,
} from '@nestjs/common';
import { ApiTags, ApiOperation, ApiResponse, ApiHeader } from '@nestjs/swagger';
import { Request } from 'express';
import { PaymentsService } from './payments.service';
import { Public } from '../../core/auth/public.decorator';
import { logger } from '@kalpak/logger';

@ApiTags('Webhooks')
@Controller('webhooks')
export class WebhooksController {
  constructor(private readonly paymentsService: PaymentsService) {}

  @Public()
  @Post('razorpay')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Razorpay Test Mode Webhook Endpoint',
    description:
      'Receives asynchronous events (payment.captured, payment.failed, order.paid) from Razorpay with HMAC-SHA256 signature verification and idempotency protection.',
  })
  @ApiHeader({
    name: 'x-razorpay-signature',
    description: 'HMAC-SHA256 signature generated by Razorpay using RAZORPAY_WEBHOOK_SECRET',
    required: true,
  })
  @ApiHeader({
    name: 'x-razorpay-event-id',
    description: 'Unique identifier of the Razorpay event for idempotency',
    required: false,
  })
  @ApiResponse({ status: 200, description: 'Webhook received and processed idempotently' })
  @ApiResponse({ status: 400, description: 'Invalid signature or bad request' })
  async handleRazorpayWebhook(
    @Req() req: Request & { rawBody?: Buffer },
    @Headers('x-razorpay-signature') signature?: string,
    @Headers('x-razorpay-event-id') eventIdHeader?: string
  ) {
    if (!signature) {
      logger.warn('[Webhook] Received Razorpay webhook without x-razorpay-signature header');
      throw new BadRequestException('Missing x-razorpay-signature header');
    }

    // Extract raw body buffer or fallback to stringified body
    let rawBodyBuffer: Buffer;
    if (req.rawBody && Buffer.isBuffer(req.rawBody)) {
      rawBodyBuffer = req.rawBody;
    } else if (typeof (req as any).body === 'string') {
      rawBodyBuffer = Buffer.from((req as any).body, 'utf8');
    } else if (Buffer.isBuffer((req as any).body)) {
      rawBodyBuffer = (req as any).body;
    } else {
      rawBodyBuffer = Buffer.from(JSON.stringify((req as any).body || {}), 'utf8');
    }

    return this.paymentsService.processWebhook(rawBodyBuffer, signature, eventIdHeader);
  }
}
